---
app_name: myapp
domain_name: localhost

# Common packages
common_packages:
  - curl
  - wget
  - vim
  - htop
  - git

# Security settings (relaxed for localhost testing)
allowed_ports:
  - 22
  - 80
  - 443
  - 3001
  - 3002
  - 3003
  - 8080