---
- name: Deploy HTML Application
  hosts: webservers
  become: yes

  vars:
    app_dir: /var/www/myapp
    html_content: |
      <!DOCTYPE html>
      <html lang="en">
      <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>MyApp</title>
        <style>
          body {
            font-family: Arial, sans-serif;
            background: linear-gradient(135deg, #4facfe, #00f2fe);
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            color: white;
            text-align: center;
          }
          h1 {
            font-size: 3em;
            margin-bottom: 10px;
          }
          p {
            font-size: 1.2em;
          }
          .card {
            background: rgba(0, 0, 0, 0.6);
            padding: 40px;
            border-radius: 15px;
            box-shadow: 0 8px 16px rgba(0, 0, 0, 0.4);
          }
        </style>
      </head>
      <body>
        <div class="card">
          <h1>🚀 Welcome to MyApp!</h1>
          <p>Your web server is running successfully with Ansible + Nginx 🎉</p>
        </div>
      </body>
      </html>

  tasks:
    - name: Create application directory
      file:
        path: "{{ app_dir }}"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Deploy HTML file
      copy:
        content: "{{ html_content }}"
        dest: "{{ app_dir }}/index.html"
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Install NGINX
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Remove default Nginx site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify:
        - Reload Nginx

    - name: Configure Nginx for MyApp
      copy:
        dest: /etc/nginx/sites-available/myapp.conf
        content: |
          server {
              listen 80;
              server_name _;
              root {{ app_dir }};
              index index.html;

              location / {
                  try_files $uri $uri/ =404;
              }
          }
      notify:
        - Reload Nginx

    - name: Enable MyApp site
      file:
        src: /etc/nginx/sites-available/myapp.conf
        dest: /etc/nginx/sites-enabled/myapp.conf
        state: link
      notify:
        - Reload Nginx

    - name: Ensure NGINX is running
      service:
        name: nginx
        state: started
        enabled: yes

  handlers:
    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded
