---
- name: Configure Web Servers
  hosts: webservers
  become: no
  gather_facts: yes

  tasks:
    - name: Wait for connection
      wait_for_connection:
        timeout: 60

  roles:
    - webserver

  post_tasks:
    - name: Verify web server is running
      uri:
        url: "http://localhost:{{ app_port }}/health"
        method: GET
      delegate_to: localhost
      retries: 3
      delay: 5

- name: Configure Load Balancers
  hosts: loadbalancers
  become: no
  gather_facts: yes

  tasks:
    - name: Wait for connection
      wait_for_connection:
        timeout: 60

  roles:
    - loadbalancer

  post_tasks:
    - name: Verify load balancer is running
      uri:
        url: "http://localhost:{{ nginx_port }}/health-lb"
        method: GET
      delegate_to: localhost
      retries: 3
      delay: 5

    - name: Test load balancing
      uri:
        url: "http://localhost:{{ nginx_port }}/"
        method: GET
      delegate_to: localhost
      register: lb_test
      retries: 3
      delay: 2

    - name: Show load balancer test result
      debug:
        var: lb_test.json
      when: lb_test.json is defined
