---
- name: restart nginx
  service:
    name: nginx
    state: restarted
  become: yes

- name: reload systemd
  systemd:
    daemon_reload: yes
  become: yes

- name: restart application
  service:
    name: "{{ app_name }}"
    state: restarted
  become: yes